### ISSUE TITLE
Typography Improvement

### ISSUE THREAD

**Issue by yumeforever** [apache/incubator-openwhisk-website#160]
Hello guys, 
To improve readability of the text, I would like to suggest a quick change from Lato Sans Light to Regular.
https://fonts.google.com/specimen/Lato

Cheers,
Morgana

**Comment by mrutkows** [comment]
Hi Morgana, can you tell us what file(s) this would be set in (CSS?).

**Comment by krook** [comment]
@mrutkows I believe it would just change here: https://github.com/openwhisk/openwhisk.github.io/blob/master/_scss/config/_variables.scss#L27

**Comment by mrutkows** [comment]
This issue is no longer applicable subsequent to the website redesign.
