### ISSUE TITLE
Set up custom domain for our medium.com 

### ISSUE THREAD

**Issue by andreasnauerz** [apache/incubator-openwhisk-website#162]
We currently blog about OpenWhisk via medium.com where we can be reached via https://medium.com/openwhisk
This is also where we link to from openwhisk.org

Wouldn't it be cooler to use a domain like openwhisk.org/blog instead?

Seems to be possible:
https://help.medium.com/hc/en-us/articles/214110127-About-custom-domains

Thoughts?

**Comment by krook** [comment]
I like this idea @nauerz-ibm. We could continue to use the Medium icon link, but should also add a Blog link as a high level nav item (under "Community" in the proposed content reorg in Issue #123).

Key to this is not only managing the [DNS with Medium](https://help.medium.com/hc/en-us/requests/new?ticket_form_id=165177), but also updating the design on [Medium itself](https://blog.medium.com/how-to-make-your-publication-look-great-9d788f0fcb2f#.2bsq5g58w).

**Comment by mrutkows** [comment]
I am closing this issue as this is not generally supported at Apache (as they would have to host and maintain derivative project path URLs.
