### ISSUE TITLE
Gender representation on the home page

### ISSUE THREAD

**Issue by mcwhittemore** [apache/incubator-openwhisk-website#166]
I just found out about this via the `serverless` email announcement. Really sweet stuff here, thanks for all the hard work.

When scrolling down the Home page I noticed that most of the people appear to be male. I'll be the first to admit that this is my own basis at looking at these images, but I thought I'd mention it if only to have this closed with some note about how I'm wrong.

Specifically, my concern is that the first 3 people on the site all appear to be male and it is not until one gets to the bottom that there is a person who appears to be female.

![image](https://cloud.githubusercontent.com/assets/1551510/22444527/55f935c2-e711-11e6-81dc-235ba60580c5.png)

![image](https://cloud.githubusercontent.com/assets/1551510/22444541/62422a14-e711-11e6-90d1-727df34e599d.png)

Regards,
Matthew

**Comment by krook** [comment]
@yumeforever Is this something you can look at?

**Comment by csantanapr** [comment]
@mcwhittemore Thanks for bringing this up, I have not art skills , but I'm afraid I will do a terrible job using gimp :-)

I think @yumeforever could look into finding a way to update it.

**Comment by mcwhittemore** [comment]
@csantanapr - I thought about trying to make the PR myself but my gimp skills leave much to be desired too.

Its cool to see so traction here.

**Comment by mrutkows** [comment]
The new website has removed all such images; therefore these issues no longer exist.
