### ISSUE TITLE
SSL certificate is not valid?

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-website#167]
https://openwhisk.org/ reports an invalid certificate.

**Comment by krook** [comment]
We need to get a certificate and work to configure GitHub Pages if needed.

**Comment by mrutkows** [comment]
SSL certs. for custom domain discussion... https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8

**Comment by csantanapr** [comment]
we are using apache ssl certs with the redirect to https://openwhisk.incubator.apache.org/
