### ISSUE TITLE
Update GitHub link to Apache org. and suggest new page for "code" (repos).

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-website#217]
As we are not yet fully migrated as of May 8th, this can be problematic...

In addition, we need to allow users to find all "openwhisk" labelled repos. under a much larger Apache org. within GitHub.  As supplied by Carlos, the following link (with query) can find them all

https://github.com/apache?utf8=%E2%9C%93&q=openwhisk

I would suggest we create a dedicated page (on top-level, menu with drop-down that takes you to a new page) listing and describing all repos. as well since we lost this "family" feeling under GitHub structure of Apache.

**Comment by mrutkows** [comment]
How do we do something like this: https://cwiki.apache.org/confluence/display/OPENWHISK/Subproject+listing

in the Documentation page?  Section "Project structure"

- List of repos. (as in Wiki)

Also see ,main repo. README: https://github.com/apache/incubator-openwhisk

Repository Structure

The OpenWhisk system is built from a number of components. The picture below groups the components by their GitHub repos. Please open issues for a component against the appropriate repo (if in doubt just open against the main openwhisk repo).

component/repo mapping

**Comment by mrutkows** [comment]
link to https://github.com/apache/incubator-openwhisk/blob/master/docs/dev/modules.md and update to make more current.

**Comment by pritidesai** [comment]
Done with PR #299
