### ISSUE TITLE
Top github button needs updating

### ISSUE THREAD

**Issue by ioana-blue** [apache/incubator-openwhisk-website#242]
The webpage has two github logo buttons: top and bottom. The bottom one takes me to the actual github repo for openwhisk. The top one takes me to the old repo that has a non-clickable link to the new repo. Make the top button behave like the bottom one. 

I noticed this (hope it helps):
  *  the link on the top github logo is: https://github.com/openwhisk/
  * the link on the bottom logo points to: https://github.com/openwhisk/openwhisk

**Comment by krook** [comment]
Looks like @mrutkows addressed this in https://github.com/apache/incubator-openwhisk-website/commit/583d82673471e5c815fbf6fc81f326813b61deb4 but Jekyll hasn't rebuilt the site to reflect the changes? cc @csantanapr

**Comment by krook** [comment]
Looks like the are the same now. Can we please close @mrutkows @csantanapr
