### ISSUE TITLE
Bad link: Events/Resources/Tutorials

### ISSUE THREAD

**Issue by crow15** [apache/incubator-openwhisk-website#250]
The Resources/Tutorials menu item on http://openwhisk.incubator.apache.org/events.html page is bad link: https://github.com/apache/incubator-openwhisk-/opennal-resources#workshops

**Comment by serverlessnomad** [comment]
This link is bad on other pages as well, such as developers.html

Should be:

https://github.com/apache/incubator-openwhisk-external-resources#tutorials
