### ISSUE TITLE
Need to provide links/method to point to releases

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-website#274]
It is an Apache requirement, now that we have an official release, to provide the link to it (and future releases) from our project website. We need a methodology to do so; I would prefer deriving a dynamic list in a widget/frame on along the right column of the main page (and plan to include other widgets above/below it) without taking up too much vertical space.

Having said this preference, we have spent lots of time to assure that the CSS layouts work on tablets and even phone form factors. We need a solution that scales with at least these 3 appx. screen size in mind.

**Comment by mrutkows** [comment]
IMO, we should do a "dropdown" from the "Downloads" menu on the home page like shown here: https://kubernetes.io/

with a menu of versioned releases ...
