### ISSUE TITLE
Need FAQ to adhere to ASF reqs.

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-website#294]
Perhaps provide a link from Documentation page?

[] FAQ: frequently asked questions are answered here.

the old FAQ (before redesign) was not very useful, we need one that is better in quality.

**Comment by mrutkows** [comment]
Note Spark, has a Menuitem "FAQ" (under Documentation menu), perhaps we can simply link on our main Documentation page?
https://spark.apache.org/

**Comment by pritidesai** [comment]
Fixed with PR #313
