### ISSUE TITLE
Architecture Diagram is too large of a file size

### ISSUE THREAD

**Issue by bbrowning** [apache/incubator-openwhisk-website#295]
The file OW-Abstract Architecture Diagram.png shown on the root page is 5.5MB! Given that it's shown at a fairly small size on that page, we should have a resized version of this image that's a few hundred kilobytes or less.

**Comment by mrutkows** [comment]
@bbrowning PR https://github.com/apache/incubator-openwhisk-website/pull/307 should have reduced all illustrations to < 300kb (runtimes is now 200kb), does this address this issue so we can close it?

**Comment by mrutkows** [comment]
Closing for now, we can see if we can make smaller in future if necessary, but we got the major culprits...

**Comment by bbrowning** [comment]
Much better - my mobile data thanks you!
