### ISSUE TITLE
FAQ is MIA

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-website#300]
There use to be a faq on the website https://openwhisk.apache.org/faq.html

Now is lost with the new design, can we bring it back and same url?
Doing a Google search "Openwhisk FAQ" it returns the url as a hit but now is 404

https://github.com/apache/incubator-openwhisk-website/commit/ade2a80be9fb6a515b1bbec42a81f69a9e18ecf4#diff-4a1318da06786ac52626178ca960109e

Thanks to Michael Marth from Adobe for finding this as he wanted to edit and add more answers.

**Comment by pritidesai** [comment]
Duplicate of issue #294

**Comment by csantanapr** [comment]
Thanks @pritidesai I didn't see #294 closing this one
