### ISSUE TITLE
Point to lists.apache.org for archives

### ISSUE THREAD

**Issue by bdelacretaz** [apache/incubator-openwhisk-website#301]
On the http://openwhisk.apache.org/community.html page, it would be better to link to https://lists.apache.org/list.html?dev@openwhisk.apache.org instead of  http://mail-archives.apache.org - the lists.apache.org service is much more convenient, and people can also reply directly there.

**Comment by mrutkows** [comment]
Fixed in https://github.com/apache/incubator-openwhisk-website/pull/318
