### ISSUE TITLE
Prioritize linking to the runtimes in the documentation above linking to the runtime repositories

### ISSUE THREAD

**Issue by Juice10** [apache/incubator-openwhisk-website#306]
In the ["Developers" section](http://openwhisk.incubator.apache.org/documentation.html#developers) of the documentation, the first time you see the runtimes mentioned is in the ["Actions" section](http://openwhisk.incubator.apache.org/documentation.html#actions). The links to these supported programming languages go straight to the GitHub repo for the runtime. Since this is part the developers section I would like to propose linking to documentation on the language instead, from there you can always get to the repo via the provided links. 

This also really helps with scanning the document. When quickly scanning the documentation, you click the first link you see for the language you are interested in and you'll get the documentation for it as opposed to the runtime code.

# Example change

PHP link will refer to http://openwhisk.incubator.apache.org/documentation.html#php as opposed to https://github.com/apache/incubator-openwhisk-runtime-php/blob/master/README.md

**Comment by pritidesai** [comment]
@Juice10 I am not sure if I understand the change, the purpose of a link called "PHP" under "Actions" section is to demonstrate how to create write functions and create actions using PHP runtime. 

![screen shot 2018-08-14 at 2 33 47 pm](https://user-images.githubusercontent.com/206285/44119871-63568292-9fcf-11e8-82f6-6242bffdd887.png)

The PHP runtime doesnt have this information (we should update the runtime repo first IMO). The runtime repo doesnt show how to create a simple hello world action yet.

![screen shot 2018-08-14 at 2 37 25 pm](https://user-images.githubusercontent.com/206285/44119984-b836973e-9fcf-11e8-9a20-a46517a11d1b.png)

**Comment by Juice10** [comment]
@pritidesai yeah sorry about that, it's kind of hard to explain in text so I decided to record a little video of it to explain exactly what I mean. Let me know if this clarifies things: 
https://monosnap.com/file/ypOoOSjiIxsMNmPsOhOpqutQN1GvUL

**Comment by pritidesai** [comment]
wow, thats awesome, let me check the video 👍

**Comment by pritidesai** [comment]
yeah I understand what you are saying now. I had added the links to all different runtimes under Actions section to kind of show listing of supported runtimes and pointing them to repo in one single place:

![screen shot 2018-08-14 at 2 58 02 pm](https://user-images.githubusercontent.com/206285/44120852-92ed9632-9fd2-11e8-8600-492d34844d13.png)

But after adding [Project Structure](http://openwhisk.apache.org/documentation.html#project-structure), I think we can change those links to point it to respective sections on the doc page as you requested.

**Comment by pritidesai** [comment]
Fixed with PR #309
